import { dirname, relative, sep } from 'node:path'
import type { ScannedRoute } from './scan'

export type EmitRouteTreeOptions = {
  routes: Array<ScannedRoute>
  generatedRouteTree: string
  routesDirectory: string
  runtimeImport?: string
  rootImport?: string
}

function toPosix(value: string) {
  return value.split(sep).join('/')
}

function importSpecifier(fromFile: string, toFile: string) {
  let spec = toPosix(relative(dirname(fromFile), toFile)).replace(/\.[^.]+$/, '')
  if (!spec.startsWith('.')) spec = `./${spec}`
  return spec
}

function jsString(value: string) {
  return JSON.stringify(value)
}

export function emitRouteTreeRuntime(options: EmitRouteTreeOptions): string {
  const runtimeImport = options.runtimeImport ?? '@anonrig/router-core'
  const children = options.routes.filter((route) => !route.isRoot)
  const root = options.routes.find((route) => route.isRoot)

  const lines: Array<string> = [
    '/* eslint-disable */',
    '',
    '// Generated by @anonrig/router-generator. Do not edit.',
    '// Runtime only: types live in routeTree.types.ts and are erased from the bundle.',
    '',
    `import { createRoute, createSlotRoute } from '${runtimeImport}'`,
  ]

  if (root) {
    lines.push(
      `import { Route as rootRoute } from '${importSpecifier(options.generatedRouteTree, root.filePath)}'`,
    )
  } else {
    lines.push(`import { createRootRoute } from '${options.rootImport ?? runtimeImport}'`)
    lines.push('const rootRoute = createRootRoute()')
  }

  lines.push('')
  lines.push('const byId = Object.create(null)')
  lines.push('byId.__root__ = rootRoute')
  lines.push('const children = Object.create(null)')
  lines.push('')
  lines.push('function add(key, id, path, parentId, load, slot) {')
  lines.push('  const getParentRoute = () => byId[parentId]')
  lines.push(
    '  const route = slot ? createSlotRoute({ getParentRoute, slot }) : key.includes("/@") || key.startsWith("/@") ? createSlotRoute({ getParentRoute }) : createRoute({ getParentRoute })',
  )
  lines.push(
    '  route.update(path === undefined ? { id, getParentRoute } : { id, path, getParentRoute })',
  )
  lines.push('  route.lazy(async () => {')
  lines.push('    const mod = await load()')
  lines.push('    const loaded = mod.Route ?? mod.default')
  lines.push('    return { options: { id: key, ...loaded?.options } }')
  lines.push('  })')
  lines.push('  route._lazyOptions = true')
  lines.push('  byId[key] = route')
  lines.push('  ;(children[parentId] ??= []).push(route)')
  lines.push('}')
  lines.push('')

  for (const route of children) {
    const spec = importSpecifier(options.generatedRouteTree, route.filePath)
    const path = route.path === undefined ? 'undefined' : jsString(route.path)
    const slot = route.isSlotRoot && route.slot ? jsString(route.slot) : 'undefined'
    lines.push(
      `add(${jsString(route.key)}, ${jsString(route.id)}, ${path}, ${jsString(route.parentId)}, () => import(${jsString(spec)}), ${slot})`,
    )
  }

  lines.push('')
  lines.push('for (const id in children) byId[id]._addFileChildren(children[id])')
  lines.push('')
  lines.push('export const routeTree = rootRoute')
  lines.push("export type { FileRouteTypes } from './routeTree.types'")
  lines.push('')
  return lines.join('\n')
}

export function emitRouteTreeTypes(options: Pick<EmitRouteTreeOptions, 'routes'>): string {
  const children = options.routes.filter((route) => !route.isRoot)
  const byFullPath: Array<string> = []
  const byTo: Array<string> = []
  const byId: Array<string> = ["    '__root__': {}"]
  const byPath: Array<string> = []

  for (const route of children) {
    const fullPath =
      route.path === undefined ? route.key.replace(/\/_[^/]+/g, '') || '/' : route.key
    const to = fullPath.endsWith('/') && fullPath !== '/' ? fullPath.slice(0, -1) : fullPath
    byFullPath.push(`    ${JSON.stringify(fullPath)}: {}`)
    byTo.push(`    ${JSON.stringify(to)}: {}`)
    byId.push(`    ${JSON.stringify(route.key)}: {}`)
    byPath.push(`    ${JSON.stringify(route.key)}: {
      id: ${JSON.stringify(route.key)}
      path: ${JSON.stringify(route.path ?? '')}
      fullPath: ${JSON.stringify(fullPath)}
      preLoaderRoute: unknown
      parentRoute: unknown
    }`)
  }

  const unique = (values: Array<string>) => [...new Set(values)]

  return `/* eslint-disable */

// Generated by @anonrig/router-generator. Do not edit.
// Types only. Importing this file from runtime code is an error.

export interface FileRoutesByFullPath {
${unique(byFullPath).join('\n')}
}

export interface FileRoutesByTo {
${unique(byTo).join('\n')}
}

export interface FileRoutesById {
${unique(byId).join('\n')}
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

declare module '@anonrig/router-core' {
  interface FileRoutesByPath {
${byPath.join('\n')}
  }
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
${byPath.join('\n')}
  }
}
`
}
