import { dirname, relative, sep } from 'node:path'
import { urlPathFromId, type ScannedRoute } from './scan'

function typePath(path: string | undefined) {
  if (!path) return ''
  return path !== '/' && path.endsWith('/') ? path.slice(0, -1) : path
}

export type EmitRouteTreeOptions = {
  routes: Array<ScannedRoute>
  generatedRouteTree: string
  routesDirectory: string
  runtimeImport?: string
  rootImport?: string
  slotImport?: string
}

function toPosix(value: string) {
  return value.split(sep).join('/')
}

function importSpecifier(fromFile: string, toFile: string) {
  let spec = toPosix(relative(dirname(fromFile), toFile)).replace(/\.[^.]+$/, '')
  if (!spec.startsWith('.')) spec = `./${spec}`
  return spec
}

function jsString(value: string) {
  return JSON.stringify(value)
}

export function emitRouteTreeRuntime(options: EmitRouteTreeOptions): string {
  const runtimeImport = options.runtimeImport ?? 'speedy-router-core'
  const children = options.routes.filter((route) => !route.isRoot)
  const root = options.routes.find((route) => route.isRoot)
  const hasSlots = children.some((route) => route.isSlotRoot || route.key.includes('/@'))
  const slotImport =
    options.slotImport ??
    (runtimeImport === 'speedy-router' || runtimeImport.includes('react-router')
      ? runtimeImport
      : 'speedy-router')

  const lines: Array<string> = [
    '/* eslint-disable */',
    '',
    '// Generated by speedy-router-generator. Do not edit.',
    '// Runtime only: types live in routeTree.types.ts and are erased from the bundle.',
    '',
    hasSlots
      ? slotImport === runtimeImport
        ? `import { createRoute, createSlotRoute } from '${runtimeImport}'`
        : `import { createRoute } from '${runtimeImport}'\nimport { createSlotRoute } from '${slotImport}'`
      : `import { createRoute } from '${runtimeImport}'`,
  ]

  if (root) {
    lines.push(
      `import { Route as rootRoute } from '${importSpecifier(options.generatedRouteTree, root.filePath)}'`,
    )
  } else {
    lines.push(`import { createRootRoute } from '${options.rootImport ?? runtimeImport}'`)
    lines.push('const rootRoute = createRootRoute()')
  }

  lines.push('')
  lines.push('const byId = Object.create(null)')
  lines.push('byId.__root__ = rootRoute')
  lines.push('const children = Object.create(null)')
  lines.push('')
  lines.push(
    hasSlots
      ? 'function add(key, id, path, parentId, load, slot) {'
      : 'function add(key, id, path, parentId, load) {',
  )
  lines.push('  const getParentRoute = () => byId[parentId]')
  lines.push(
    hasSlots
      ? '  const route = slot ? createSlotRoute({ getParentRoute, slot }) : key.includes("/@") ? createSlotRoute({ getParentRoute }) : createRoute({ getParentRoute })'
      : '  const route = createRoute({ getParentRoute })',
  )
  lines.push(
    '  route.update(path === undefined ? { id, getParentRoute } : { id, path, getParentRoute })',
  )
  lines.push('  route.lazy(async () => {')
  lines.push('    const mod = await load()')
  lines.push('    const loaded = mod.Route ?? mod.default')
  lines.push('    return { options: { id: key, ...loaded?.options } }')
  lines.push('  })')
  lines.push('  route._lazyOptions = true')
  lines.push('  byId[key] = route')
  lines.push('  ;(children[parentId] ??= []).push(route)')
  lines.push('}')
  lines.push('')

  for (const route of children) {
    const spec = importSpecifier(options.generatedRouteTree, route.filePath)
    const path = route.path === undefined ? 'undefined' : jsString(route.path)
    const args = [
      jsString(route.key),
      jsString(route.id),
      path,
      jsString(route.parentId),
      `() => import(${jsString(spec)})`,
    ]
    if (hasSlots) args.push(route.isSlotRoot && route.slot ? jsString(route.slot) : 'undefined')
    lines.push(`add(${args.join(', ')})`)
  }

  lines.push('')
  lines.push('for (const id in children) byId[id]._addFileChildren(children[id])')
  lines.push('')
  lines.push('export const routeTree = rootRoute')
  lines.push("export type { FileRouteTypes } from './routeTree.types'")
  lines.push('')
  return lines.join('\n')
}

export function emitRouteTreeTypes(options: Pick<EmitRouteTreeOptions, 'routes'>): string {
  const children = options.routes.filter((route) => !route.isRoot)
  const byFullPath: Array<string> = []
  const byTo: Array<string> = []
  const byId: Array<string> = ["    '__root__': {}"]
  const byPath: Array<string> = []

  for (const route of children) {
    const fullPath = urlPathFromId(route.key) ?? '/'
    const to = fullPath.endsWith('/') && fullPath !== '/' ? fullPath.slice(0, -1) : fullPath
    byFullPath.push(`    ${JSON.stringify(fullPath)}: {}`)
    byTo.push(`    ${JSON.stringify(to)}: {}`)
    byId.push(`    ${JSON.stringify(route.key)}: {}`)
    byPath.push(`    ${JSON.stringify(route.key)}: {
      id: ${JSON.stringify(route.key)}
      path: ${JSON.stringify(typePath(route.path))}
      fullPath: ${JSON.stringify(fullPath)}
      preLoaderRoute: unknown
      parentRoute: unknown
    }`)
  }

  const unique = (values: Array<string>) => [...new Set(values)]

  return `/* eslint-disable */

// Generated by speedy-router-generator. Do not edit.
// Types only. Importing this file from runtime code is an error.

export interface FileRoutesByFullPath {
${unique(byFullPath).join('\n')}
}

export interface FileRoutesByTo {
${unique(byTo).join('\n')}
}

export interface FileRoutesById {
${unique(byId).join('\n')}
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

declare module 'speedy-router-core' {
  interface FileRoutesByPath {
${byPath.join('\n')}
  }
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
${byPath.join('\n')}
  }
}
`
}
